services:
  mysql:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: population_app
    command: ["--all"]
    environment:
      DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: